// lib/words.ts

export type WordEntry = {
  word: string;
  hint: string; // single hint shown to the impostor
};

export const WORDS: WordEntry[] = [
  // Nepal, Australia, India, household, actors, diverse, indirect hints, Nepali included

  // Household items
  { word: "PRESSURE COOKER (प्रेसर कुकर)", hint: "WHISTLE (सिटी)" },
  { word: "MATTRESS (गद्दा)", hint: "SPRING (स्प्रिङ्ग)" },
  { word: "MOP (पोछा)", hint: "HANDLE (ह्याण्डल)" },
  { word: "THERMOS (थर्मस)", hint: "PICNIC (पिकनिक)" },
  { word: "IRON (इस्त्री)", hint: "SMOOTH (समतल)" },
  { word: "BUCKET (बाल्टी)", hint: "WELL (इनार)" },
  { word: "MIRROR (ऐना)", hint: "REFLECTION (प्रतिबिम्ब)" },
  { word: "CURTAIN (पर्दा)", hint: "WINDOW (झ्याल)" },
  { word: "BLENDER (मिक्सर)", hint: "SPEED (गति)" },
  { word: "UMBRELLA (छाता)", hint: "SHADE (छायाँ)" },
  { word: "TOOTHBRUSH (दाँत माझ्ने ब्रस)", hint: "BRISTLE (कपाल)" },
  { word: "STOVE (चुलो)", hint: "FLAME (आगो)" },
  { word: "BROOM (कुचो)", hint: "SWEEP (बोक्रा)" },
  { word: "LOCKER (लकर)", hint: "SECRET (गुप्त)" },
  { word: "SOFA (सोफा)", hint: "GUEST (अतिथि)" },
  { word: "BEDSHEET (चादर)", hint: "PATTERN (ढाँचा)" },
  { word: "BULB (बत्ती)", hint: "GLASS (सिसा)" },
  { word: "FRIDGE (फ्रिज)", hint: "COLD (चिसो)" },
  { word: "CUPBOARD (अलमारी)", hint: "STORAGE (भण्डारण)" },
  { word: "TABLE (टेबल)", hint: "MEETING (भेटघाट)" },

  // Nepali, Indian, Australian actors
  { word: "RAJESH HAMAL (राजेश हमाल)", hint: "HEIGHT (उचाइ)" },
  { word: "PRIYANKA KARKI (प्रियंका कार्की)", hint: "DANCE (नाच)" },
  { word: "ANIL KAPOOR (अनिल कपूर)", hint: "MOUSTACHE (जुँगा)" },
  { word: "DEEPIKA PADUKONE (दीपिका पादुकोण)", hint: "TALL (लामो)" },
  { word: "AMITABH BACHCHAN (अमिताभ बच्चन)", hint: "VOICE (स्वर)" },
  { word: "CHRIS HEMSWORTH (क्रिस हेम्सवर्थ)", hint: "HAMMER (हथौडा)" },
  { word: "JACQUELINE FERNANDEZ (ज्याकलिन फर्नान्डेज)", hint: "SRI LANKA (श्रीलंका)" },
  { word: "KANGANA RANAUT (कंगना रनौत)", hint: "QUEEN (रानी)" },
  { word: "SONAM KAPOOR (सोनम कपूर)", hint: "FASHION (फेसन)" },
  { word: "MANISHA KOIRALA (मनीषा कोइराला)", hint: "CANCER (क्यान्सर)" },
  { word: "HEMANTA RANA (हेमन्त राणा)", hint: "SONG (गीत)" },
  { word: "KATE BLANCHETT (केट ब्लान्चेट)", hint: "AWARD (पुरस्कार)" },
  { word: "SUSHANT SINGH RAJPUT (सुशान्त सिंह राजपूत)", hint: "STAR (तारा)" },
  { word: "MIRANDA KERR (मिरान्डा केर)", hint: "MODEL (मोडल)" },
  { word: "BIPIN KARKI (विपिन कार्की)", hint: "ACTOR (अभिनेता)" },
  { word: "RANBIR KAPOOR (रणबीर कपूर)", hint: "ROCKSTAR (रकस्टार)" },
  { word: "KATRINA KAIF (कट्रिना कैफ)", hint: "BIRTHDAY (जन्मदिन)" },
  { word: "SHERPA (शेर्पा)", hint: "GUIDE (मार्गदर्शक)" },

  // Nepal, Australia, India - places, food, culture, nature
  { word: "EVEREST (सगरमाथा)", hint: "FLAG (झण्डा)" },
  { word: "KANGAROO (कंगारू)", hint: "JUMP (फड्कनु)" },
  { word: "SYDNEY (सिड्नी)", hint: "BRIDGE (पुल)" },
  { word: "TAJ MAHAL (ताज महल)", hint: "WHITE (सेतो)" },
  { word: "DIDGERIDOO (डिजेरिडू)", hint: "SOUND (ध्वनि)" },
  { word: "POKHARA (पोखरा)", hint: "BOAT (डुंगा)" },
  { word: "KOALA (कोआला)", hint: "TREE (रुख)" },
  { word: "GANGES (गंगा)", hint: "RITUAL (कर्मकाण्ड)" },
  { word: "LAMJUNG (लमजुङ)", hint: "HILL (डाँडा)" },
  { word: "OPERA HOUSE (ओपेरा हाउस)", hint: "SHELL (शंख)" },
  { word: "DHAL BHAT (दाल भात)", hint: "PLATE (थाल)" },
  { word: "CRICKET (क्रिकेट)", hint: "PITCH (पिच)" },
  { word: "KATHMANDU (काठमाडौं)", hint: "VALLEY (उपत्यका)" },
  { word: "BILLABONG (बिलाबोंग)", hint: "WATER (पानी)" },
  { word: "BUNGEE (बन्जी)", hint: "ROPE (डोरी)" },
  { word: "MOMO (म:म:)", hint: "STEAM (बाफ)" },
  { word: "TIGER (बाघ)", hint: "STRIPE (धर्सा)" },
  { word: "KATHMANDU DURBAR (काठमाडौं दरबार)", hint: "SQUARE (चोक)" },
  { word: "SURFBOARD (सर्फबोर्ड)", hint: "WAX (मैन)" },
  { word: "HIMALAYA (हिमालय)", hint: "SNOW (हिउँ)" },
  { word: "BAGPIPES (ब्यागपाइप्स)", hint: "AIR (हावा)" },
  { word: "RICKSHAW (रिक्सा)", hint: "BELL (घण्टी)" },
  { word: "KANGCHENJUNGA (कञ्चनजङ्घा)", hint: "THIRD (तेस्रो)" },
  { word: "SARI (साडी)", hint: "CLOTH (कपडा)" },
  { word: "BOOMERANG (बुमेराङ)", hint: "RETURN (फर्कनु)" },
  { word: "BUDDHA (बुद्ध)", hint: "PEACE (शान्ति)" },
  { word: "KATHMANDU (काठमाडौं)", hint: "TEMPLE (मन्दिर)" },
  { word: "KOALA (कोआला)", hint: "EUCALYPTUS (युकलिप्टस)" },
  { word: "GORKHA (गोरखा)", hint: "BRAVE (बहादुर)" },
  { word: "MELBOURNE (मेलबर्न)", hint: "LANE (गल्ली)" },
  { word: "BIRGUNJ (वीरगञ्ज)", hint: "BORDER (सीमा)" },
  { word: "KATHMANDU (काठमाडौं)", hint: "DUST (धुलो)" },
  { word: "KANGAROO (कंगारू)", hint: "POUCH (थैली)" },
  { word: "BHAKTAPUR (भक्तपुर)", hint: "CURD (दही)" },
  { word: "TANDOOR (तन्दूर)", hint: "CLAY (माटो)" },
  { word: "BUNGEE (बन्जी)", hint: "HEIGHT (उचाइ)" },
  { word: "BAGMATI (बागमती)", hint: "FLOW (बहाव)" },
  { word: "SURFBOARD (सर्फबोर्ड)", hint: "BALANCE (सन्तुलन)" },
  { word: "BIRATNAGAR (विराटनगर)", hint: "PLANE (जहाज)" },
  { word: "KATHMANDU (काठमाडौं)", hint: "TRAFFIC (ट्राफिक)" },
  { word: "KOALA (कोआला)", hint: "SLEEP (सुत्नु)" },
  { word: "EVEREST (सगरमाथा)", hint: "PEAK (शिखर)" },
  { word: "TAJ MAHAL (ताज महल)", hint: "LOVE (माया)" },
  { word: "BUNGEE (बन्जी)", hint: "FEAR (डर)" },
  { word: "MOMO (म:म:)", hint: "SAUCE (अचार)" },
  { word: "TIGER (बाघ)", hint: "JUNGLE (जंगल)" },
  { word: "KATHMANDU DURBAR (काठमाडौं दरबार)", hint: "KING (राजा)" },
  { word: "SURFBOARD (सर्फबोर्ड)", hint: "OCEAN (समुन्द्र)" },
  { word: "HIMALAYA (हिमालय)", hint: "COLD (चिसो)" },
  { word: "BAGPIPES (ब्यागपाइप्स)", hint: "SCOTLAND (स्कटल्याण्ड)" },
  { word: "RICKSHAW (रिक्सा)", hint: "WHEEL (पाङ्ग्रा)" },
  { word: "KANGCHENJUNGA (कञ्चनजङ्घा)", hint: "SNOW (हिउँ)" },
  { word: "SARI (साडी)", hint: "COLOR (रंग)" },
  { word: "BOOMERANG (बुमेराङ)", hint: "THROW (फ्याँक्नु)" },
  { word: "BUDDHA (बुद्ध)", hint: "MEDITATE (ध्यान)" },
  { word: "KATHMANDU (काठमाडौं)", hint: "STUPA (गुम्बा)" },
  { word: "KOALA (कोआला)", hint: "FUR (रौं)" },
  { word: "GORKHA (गोरखा)", hint: "KNIFE (खुकुरी)" },
  { word: "MELBOURNE (मेलबर्न)", hint: "ART (कला)" },
  { word: "BIRGUNJ (वीरगञ्ज)", hint: "TRADE (व्यापार)" },
  { word: "KATHMANDU (काठमाडौं)", hint: "RINGROAD (रिङ्गरोड)" },
  { word: "KANGAROO (कंगारू)", hint: "TAIL (पुच्छर)" },
  { word: "BHAKTAPUR (भक्तपुर)", hint: "POTTERY (माटोका भाँडा)" },
  { word: "TANDOOR (तन्दूर)", hint: "HEAT (तातो)" },
  { word: "BUNGEE (बन्जी)", hint: "BRIDGE (पुल)" },
  { word: "BAGMATI (बागमती)", hint: "TEMPLE (मन्दिर)" },
  { word: "SURFBOARD (सर्फबोर्ड)", hint: "WAVE (छाल)" },
  { word: "BIRATNAGAR (विराटनगर)", hint: "INDUSTRY (उद्योग)" },

  // More household, food, and random
  { word: "DAL (दाल)", hint: "LENTIL (मसुरो)" },
  { word: "RICE COOKER (चामल पकाउने मेसिन)", hint: "SWITCH (स्विच)" },
  { word: "FAN (पंखा)", hint: "BLADE (पङ्खा)" },
  { word: "TELEVISION (टेलिभिजन)", hint: "REMOTE (रिमोट)" },
  { word: "CHAIR (कुर्सी)", hint: "LEG (खुट्टा)" },
  { word: "CUP (कप)", hint: "HANDLE (ह्याण्डल)" },
  { word: "PLATE (थाल)", hint: "ROUND (गोलो)" },
  { word: "SPOON (चम्चा)", hint: "SILVER (चाँदी)" },
  { word: "PILLOW (तकिया)", hint: "SOFT (नरम)" },
  { word: "BAG (झोला)", hint: "ZIP (जिप)" },
  { word: "LAMP (दियो)", hint: "OIL (तेल)" },
  { word: "TOOTHPASTE (दाँत माझ्ने पेस्ट)", hint: "MINT (पुदिना)" },
  { word: "SOAP (साबुन)", hint: "BUBBLE (फोका)" },
  { word: "TOWEL (तौलिया)", hint: "DRY (सुक्खा)" },
  { word: "CLOCK (घडी)", hint: "TICK (टिक)" },
  { word: "DOOR (ढोका)", hint: "KNOCK (ठकठक)" },
  { word: "WINDOW (झ्याल)", hint: "GLASS (सिसा)" },
  { word: "CARPET (गुन्द्रुक)", hint: "FLOOR (भुइँ)" },
  { word: "BASKET (टोकरी)", hint: "HANDLE (ह्याण्डल)" },
  { word: "JUG (जग)", hint: "POUR (हाल्नु)" },
  { word: "MATCHBOX (सलाईको बट्टा)", hint: "STRIKE (घस्नु)" },
  { word: "CANDLE (मैनबत्ती)", hint: "WAX (मैन)" },
  { word: "BELL (घण्टी)", hint: "RING (घन्टी बज्नु)" },
  { word: "BOWL (कटोरी)", hint: "ROUND (गोलो)" },
  { word: "BROOM (कुचो)", hint: "DUST (धुलो)" },
  { word: "MUG (मग)", hint: "COFFEE (कफी)" },
  { word: "TRAY (ट्रे)", hint: "CARRY (बोक्नु)" },
  { word: "STOOL (पाउदान)", hint: "SHORT (छोटो)" },
  { word: "CUSHION (कुशन)", hint: "DECOR (सजावट)" },
  { word: "BEDSHEET (चादर)", hint: "COTTON (कपास)" },
  { word: "CURTAIN (पर्दा)", hint: "ROD (डण्डी)" },
  { word: "DUSTBIN (फोहोरदानी)", hint: "COVER (ढकनी)" },
  { word: "MIRROR (ऐना)", hint: "FACE (अनुहार)" },
  { word: "KEY (चाबी)", hint: "LOCK (ताला)" },
  { word: "SHOE (जुत्ता)", hint: "LACE (फिता)" },
  { word: "SLIPPER (चप्पल)", hint: "RUBBER (रबर)" },
  { word: "BAG (झोला)", hint: "STRAP (पट्टा)" },
  { word: "BOTTLE (बोतल)", hint: "CAP (ढकनी)" },
  { word: "NAPKIN (रुमाल)", hint: "WIPE (पुछ्नु)" },
  { word: "FORK (काँटा)", hint: "PRONG (काँटा)" },
  { word: "KNIFE (चक्कु)", hint: "SHARP (धारिलो)" },
  { word: "GLASS (गिलास)", hint: "TRANSPARENT (पारदर्शी)" },
  { word: "STRAW (पाइप)", hint: "SUCK (चुस्नु)" },
  { word: "BASKET (टोकरी)", hint: "FRUIT (फलफूल)" },
  { word: "CLOTHES (लुगा)", hint: "WARDROBE (अलमारी)" },
  { word: "TROUSERS (पाइन्ट)", hint: "POCKET (खल्ती)" },
  { word: "SHIRT (सर्ट)", hint: "BUTTON (बटन)" },
  { word: "SAREE (साडी)", hint: "BORDER (किनार)" },
  { word: "DRESS (ड्रेस)", hint: "PARTY (पार्टी)" },
  { word: "JACKET (ज्याकेट)", hint: "ZIPPER (जिपर)" },
  { word: "CAP (टोपी)", hint: "SHADE (छायाँ)" },
  { word: "SCARF (स्कार्फ)", hint: "NECK (घाँटी)" },
  { word: "SOCKS (मोजा)", hint: "PAIR (जोडी)" },
  { word: "BLANKET (कम्बल)", hint: "WARM (न्यानो)" },
  { word: "QUILT (रजाई)", hint: "STITCH (सिउनु)" },
  { word: "TOWEL (तौलिया)", hint: "BATH (नुहाउने)" },
  { word: "COMB (काँगि)", hint: "HAIR (कपाल)" },
  { word: "BRUSH (ब्रस)", hint: "PAINT (रंग)" },
  { word: "SOAP (साबुन)", hint: "CLEAN (सफा)" },
  { word: "SHAMPOO (शैम्पू)", hint: "BUBBLE (फोका)" },
  { word: "TOOTHPASTE (दाँत माझ्ने पेस्ट)", hint: "TUBE (नली)" },
  { word: "RAZOR (रेजर)", hint: "BLADE (ब्लेड)" },
  { word: "MIRROR (ऐना)", hint: "WALL (पर्खाल)" },
  { word: "BUCKET (बाल्टी)", hint: "WATER (पानी)" },
  { word: "MUG (मग)", hint: "HANDLE (ह्याण्डल)" },
  { word: "JUG (जग)", hint: "POUR (हाल्नु)" },
  { word: "BOWL (कटोरी)", hint: "SOUP (सुप)" },
  { word: "PLATE (थाल)", hint: "FOOD (खाना)" },
  { word: "SPOON (चम्चा)", hint: "STIR (चलाउनु)" },
  { word: "FORK (काँटा)", hint: "EAT (खानु)" },
  { word: "KNIFE (चक्कु)", hint: "CUT (काट्नु)" },
  { word: "GLASS (गिलास)", hint: "DRINK (पिउनु)" },
  { word: "BOTTLE (बोतल)", hint: "FILL (भर्नु)" },
  { word: "TRAY (ट्रे)", hint: "SERVE (पस्कनु)" },
  { word: "BASKET (टोकरी)", hint: "CARRY (बोक्नु)" },
  { word: "DUSTBIN (फोहोरदानी)", hint: "TRASH (फोहोर)" },
  { word: "BROOM (कुचो)", hint: "SWEEP (बोक्रा)" },
  { word: "MOP (पोछा)", hint: "FLOOR (भुइँ)" },
  { word: "CLOTHES (लुगा)", hint: "WASH (धुनु)" },
  { word: "SOAP (साबुन)", hint: "LATHER (फोका)" },
  { word: "SHAMPOO (शैम्पू)", hint: "HAIR (कपाल)" },
  { word: "TOOTHBRUSH (दाँत माझ्ने ब्रस)", hint: "BRISTLE (कपाल)" },
  { word: "TOOTHPASTE (दाँत माझ्ने पेस्ट)", hint: "MINT (पुदिना)" },
  { word: "TOWEL (तौलिया)", hint: "DRY (सुक्खा)" },
  { word: "NAPKIN (रुमाल)", hint: "WIPE (पुछ्नु)" },
  { word: "COMB (काँगि)", hint: "TEETH (दाँत)" },
  { word: "RAZOR (रेजर)", hint: "SHAVE (कपाल फाल्नु)" },
  { word: "MIRROR (ऐना)", hint: "LOOK (हेर्नु)" },
  { word: "LAPTOP (ल्यापटप)", hint: "KEYBOARD (किबोर्ड)" },
  { word: "MOBILE PHONE (मोबाइल फोन)", hint: "CALL (कल)" },
  { word: "TELEVISION (टेलिभिजन)", hint: "REMOTE (रिमोट)" },
  { word: "FAN (पंखा)", hint: "BREEZE (हावा)" },
  { word: "CHAIR (कुर्सी)", hint: "SIT (बस्नु)" },
  { word: "PILLOW (थप्की)", hint: "SLEEP (सुत्नु)" },
  { word: "CARPET (गुन्द्रुक)", hint: "FLOOR (भुइँ)" },
  { word: "DOOR (ढोका)", hint: "KNOCK (ढकढक्याउनु)" },
  { word: "WINDOW (झ्याल)", hint: "GLASS (सिसा)" },
  { word: "CLOCK (घडी)", hint: "TIME (समय)" },
  { word: "CALENDAR (पात्रो)", hint: "DATE (मिति)" },
  { word: "PEN (कलम)", hint: "INK (मसी)" },
  { word: "PENCIL (पेन्सिल)", hint: "ERASER (रबर)" },
  { word: "NOTEBOOK (कापी)", hint: "WRITE (लेख्नु)" },
  { word: "BAG (झोला)", hint: "CARRY (बोक्नु)" },
  { word: "SHOES (जुता)", hint: "LACE (फिता)" },
  { word: "SLIPPERS (चप्पल)", hint: "COMFORT (सजिलो)" },
  { word: "WATCH (घडी)", hint: "WRIST (कुहिनो)" },
  { word: "RING (औंठी)", hint: "FINGER (औंला)" },
  { word: "EARRING (कानको मुन्द्रा)", hint: "EAR (कान)" },
  { word: "NECKLACE (माला)", hint: "NECK (घाँटी)" },
  { word: "BRACELET (चुरा)", hint: "HAND (हात)" },
  { word: "BANGLE (चुरा)", hint: "GLASS (सिसा)" },
  { word: "UMBRELLA (छाता)", hint: "RAIN (पानी)" },
  { word: "TORCH (टर्च)", hint: "BATTERY (ब्याट्री)" },
  { word: "CANDLE (मैनबत्ती)", hint: "WAX (मैन)" },
  { word: "MATCHBOX (सलाई)", hint: "FIRE (आगो)" },
  { word: "LAMP (दियो)", hint: "OIL (तेल)" },
  { word: "CURTAIN (पर्दा)", hint: "PRIVACY (गोपनीयता)" },
  { word: "PAINTING (चित्र)", hint: "FRAME (फ्रेम)" },
  { word: "PHOTO (फोटो)", hint: "MEMORY (स्मृति)" },
  { word: "SHELF (र्याक)", hint: "BOOK (पुस्तक)" },
  { word: "BOOK (पुस्तक)", hint: "READ (पढ्नु)" },
  { word: "MAGAZINE (पत्रिका)", hint: "ARTICLE (लेख)" },
  { word: "NEWSPAPER (समाचारपत्र)", hint: "NEWS (समाचार)" },
  { word: "PLANT (बिरुवा)", hint: "POT (गमला)" },
  { word: "FLOWER (फूल)", hint: "FRAGRANCE (सुगन्ध)" },
  { word: "VASE (फूलदानी)", hint: "DECORATION (सजावट)" },
  { word: "BELL (घण्टी)", hint: "RING (घन्टी बज्नु)" },
  { word: "STOOL (पाउढो)", hint: "SHORT (छोटो)" },
  { word: "DESK (डेस्क)", hint: "WORK (काम)" },
  { word: "ENVELOPE (खाम)", hint: "LETTER (चिठ्ठी)" },
  { word: "SCISSORS (कैंची)", hint: "CUT (काट्नु)" },
  { word: "TAPE (टेप)", hint: "STICK (टाँस्नु)" },
  { word: "GLUE (गोंद)", hint: "PASTE (टाँस्नु)" },
  { word: "STAPLER (स्टेपलर)", hint: "PIN (पिन)" },
  { word: "PIN (पिन)", hint: "SHARP (धारिलो)" },
  { word: "RULER (रूलर)", hint: "MEASURE (नाप्नु)" },
  { word: "MAP (नक्सा)", hint: "DIRECTION (दिशा)" },
  // ... (continue to thousands as needed)
];


